# $NetBSD: Makefile,v 1.33 2012/10/08 23:02:31 adam Exp $

.include "../../xfce4/xfce4/Makefile.common"

XFCE4_VERSION=	4.10.0
DISTNAME=	xfwm4-themes-${XFCE4_VERSION}
PKGNAME=	xfce4-wm-themes-${XFCE4_VERSION}
CATEGORIES=	wm
COMMENT=	Xfce window manager themes
MASTER_SITES=	http://archive.xfce.org/src/art/xfwm4-themes/4.10/

USE_LANGUAGES=	#empty

MAKE_DIRS+=	${PREFIX}/share/themes/Xfce

.include "../../mk/bsd.pkg.mk"
